repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: Ensure file ends with a newline
        exclude: ^(LICENSE|\.min\.(js|css))$
      - id: check-yaml
        name: Validate YAML files
        files: \.(yml|yaml)$
        args: [--allow-multiple-documents]
      - id: check-json
        name: Validate JSON files
        files: \.(json|json5)$
      - id: check-merge-conflict
        name: Detect merge conflict markers
      - id: detect-private-key
        name: Detect private keys in code

  # Python linter with flake8 using pyproject.toml config
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0  # or latest stable
    hooks:
      - id: pylint
        name: Python linting with pylint
        language: python
        types: [python]

  # Local hook for markdownlint-cli2 with inline logic
  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: Lint Markdown files with markdownlint-cli2 (local)
        entry: bash -c 'branch=$(git rev-parse --abbrev-ref HEAD); if [ "$branch" = "release-please--branches--main" ]; then echo "Skipping markdownlint on branch $branch"; exit 0; else npx markdownlint-cli2 "$@"; fi'
        language: system
        pass_filenames: true
        files: \.md$

  # Commit message validation (local hook)
  - repo: local
    hooks:
      - id: commitlint
        name: Commit message validation
        entry: npx commitlint --edit
        language: system
        stages: [commit-msg]
