name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit checks (skip markdownlint-cli2 on release branch)
        run: |
          BRANCH_NAME=$(echo "${{ github.head_ref }}")
          if [[ "$BRANCH_NAME" == "release-please--branches--main" ]]; then
            pre-commit run --all-files --hook-stage manual --verbose --color always | grep -v "markdownlint-cli2" || true
          else
            pre-commit run --all-files
          fi