name: Pre-commit checks

on:
  push:
    branches:
      - "*"
#   pull_request:
#     branches:
#       - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run pre-commit
        uses: pre-commit/action@v3
        with:
          # Optional: Specify the pre-commit config file
          config_file: .pre-commit-config.yaml

