name: Release on PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (for pre-commit)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit checks (skip markdownlint-cli2 on release branch)
        run: |
          BRANCH_NAME=$(echo "${{ github.head_ref }}")
          if [[ "$BRANCH_NAME" == "release-please--branches--main" ]]; then
            pre-commit run --all-files --hook-stage manual --verbose --color always | grep -v "markdownlint-cli2" || true
          else
            pre-commit run --all-files
          fi

      - name: Create Release with Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          config-file: release-please-config.json
          token: ${{ secrets.RELEASE_PAT }}

      - name: Show release output
        if: steps.release.outputs.release_created == 'true'
        run: echo "Released version ${{ steps.release.outputs.tag_name }}"
